# Generated by Django 4.2.5 on 2023-09-05 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Qq_andpassword",
            fields=[
                (
                    "qqid",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="QQ号"
                    ),
                ),
                ("password", models.CharField(max_length=15, verbose_name="密码")),
            ],
        ),
        migrations.CreateModel(
            name="Userinfo",
            fields=[
                (
                    "qqid",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="QQ号"
                    ),
                ),
                ("uername", models.CharField(max_length=10, verbose_name="昵称")),
                ("gender", models.CharField(max_length=1, verbose_name="性别")),
                ("age", models.IntegerField(verbose_name="年龄")),
                (
                    "depart",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app1.qq_andpassword",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="friend_relation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qqid", models.IntegerField(verbose_name="QQ号")),
                ("qqid_friend", models.IntegerField(verbose_name="QQ号")),
            ],
            options={"unique_together": {("qqid_friend", "qqid")},},
        ),
        migrations.CreateModel(
            name="chat_message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("send_qq", models.IntegerField(verbose_name="QQ号")),
                ("receive_qq", models.IntegerField(verbose_name="QQ号")),
                ("send_time", models.TimeField(verbose_name="发送时间")),
                ("message", models.CharField(max_length=100, verbose_name="内容")),
            ],
            options={"unique_together": {("send_qq", "receive_qq", "send_time")},},
        ),
    ]
