# Generated by Django 4.2.5 on 2023-09-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qq_andpassword",
            name="qqid",
            field=models.CharField(
                max_length=15, primary_key=True, serialize=False, verbose_name="QQ号"
            ),
        ),
    ]
