# Generated by Django 4.2.5 on 2023-09-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_remove_userinfo_depart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinfo", old_name="uername", new_name="username",
        ),
    ]
