# Generated by Django 4.2.5 on 2023-09-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_rename_uername_userinfo_username"),
    ]

    operations = [
        migrations.DeleteModel(name="Qq_andpassword",),
        migrations.AddField(
            model_name="userinfo",
            name="password",
            field=models.CharField(default="123456", max_length=15, verbose_name="密码"),
        ),
    ]
