# Generated by Django 4.2.5 on 2023-09-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_delete_qq_andpassword_userinfo_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="qqid",
            field=models.CharField(
                max_length=15, primary_key=True, serialize=False, verbose_name="QQ号"
            ),
        ),
    ]
