# Generated by Django 4.2.5 on 2023-09-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0008_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend_relation",
            name="room_id",
            field=models.IntegerField(default=1, verbose_name="房间号"),
        ),
    ]
