# Generated by Django 4.2.5 on 2023-09-08 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0009_friend_relation_room_id"),
    ]

    operations = [
        migrations.DeleteModel(name="chat_message",),
    ]
