# Generated by Django 4.2.5 on 2023-09-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0010_delete_chat_message"),
    ]

    operations = [
        migrations.RemoveField(model_name="friend_relation", name="room_id",),
        migrations.AddField(
            model_name="chat",
            name="room_id",
            field=models.CharField(default="1", max_length=15),
        ),
    ]
